### PR TITLE
If resize is cancelled, resize back to the screen size it had before entering resize mode.

### LINKED ISSUE #1391: The resize dimensions are wrongly saved when the back button on the controller is pressed
**[Affected Versions]:**
- Firefox Reality 1.2.2
- Firefox Reality 1.3 rc1
- Firefox Reality 1.3 rc2

**[Affected Platforms]:**
- Oculus Pacific Android 7.1.2 (Oculus Go)
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Click the resize icon (the icon with the 2 arrows) from the bottom right corner of the view.
2. Click one of the predefined resize buttons. 
3. Click the back button on the Oculus Go controller.
4. Observe the screen size.

**[Expected results]:**
- The screen size returns to the size it was before entering resize mode.

**[Actual results]:**
- The screen size remained at the selected predefined size.

**[Notes]:**
- The issue is also reproducible with manual resizing.
- Attached a screen recording of the issue: [link](https://drive.google.com/file/d/1_QyJSRWiv728mLz92IM7gIUsoGZ6alY3/view?usp=sharing)

### PR DESCRIPTION
**Pull request by MortimerGoro**
Fixes #1391

### CODE REVIEW

File: app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java [hunk 1]
```diff
@@ -471,10 +472,20 @@ private void enterResizeMode() {
         closeFloatingMenus();
     }
 
-    private void exitResizeMode(boolean aCommitChanges) {
+
+    enum ResizeAction {
+        KEEP_SIZE,
+        RESTORE_SIZE
```
Comment (bluemarvin) [inline app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java]: Are we using `enum` now? Do they no longer bloat the APK? We are now using both `enum` and `final int` in different places. `final int` I guess makes sense for JNI calls. Not sure if there is a benefit to `enum`?
