### PR TITLE
Fixes #2818 Make sure only one instance on the send tab dialog is alive

### LINKED ISSUE #2818: The “Send Tab to Device” prompt is displayed twice after logging in if previously the “Start Browsing” button was clicked
**[Affected Versions]:**
- Firefox Reality version 9 RC2 (37ac4cbd)
- Firefox Reality version 8.1

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- Make sure no FxA account is not logged in.

**[Steps to reproduce]:**
1. Click the hamburger menu and click the “Send Tab to Device” button.
2. Click the “Start Browsing” button.
3. Click the “View Tabs” button from the menu tray.
4. Click the send tab button on one of the tabs.
5. Click the “Sign In” button and perform a login.
6. After login is completed, dismiss the “Send Tab to Device” prompt.
7. Observe the behaviour.

**[Expected results]:**
- The “Send Tab to Device” prompt is dismissed and the website is in view.

**[Actual results]:**
- The “Send Tab to Device” prompt is dismissed and another “Send Tab to Device” prompt is displayed.

**[Notes]:**
- The issue is also reproducible in production.
- The issue is also reproducible if the login is performed from the hamburger menu.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1Qhw9p2fbIamoANGZn-4vBjNjC0I55zCt).

### PR DESCRIPTION
**Pull request by keianhzo**
Fixes #2818 Make sure only one instance on the send tab dialog is alive

### CODE REVIEW

File: app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/SendTabDialogWidget.java [hunk 1]
```diff
@@ -58,6 +68,13 @@ protected void initialize(@NonNull Context aContext) {
         mAccounts = ((VRBrowserApplication)getContext().getApplicationContext()).getAccounts();
     }
 
+    @Override
+    public void releaseWidget() {
+        super.releaseWidget();
+
+        mSendTabDialog = null;
+    }
+
```
Comment (bluemarvin) [inline app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/SendTabDialogWidget.java]: Should this be called some where? Seems like we want to create a new one when we have a new activity?
