### PR TITLE
Reuse the last frame and tracking when a VR frame is discarded in Oculus

### LINKED ISSUE #2320: Getting freeze at the immersive mode in http://moonrider.xyz
## Configuration

Firefox Reality version: FxR 7
Firefox Reality build ID: 485355cc

Hardware: 
Oculus Quest

## Steps to Reproduce

1. Visit http://moonrider.xyz using the Oculus Browser on Quest
2. Click to enter VR (glasses icon in bottom right corner) and press Begin UI.
3. Go to Punch mode, and select a music to start.

## Current Behavior

Once punching a block, the screen buffer will be freeze.

## Expected Behavior

I checked it works properly in Oculus Browser, so we should be no problem with it.

## Error Logs and Stack Traces
I would guess it would be related to gamepad haptic feedback or SurfaceTexture.

```
2019-11-19 12:38:06.770 5876-5970/org.mozilla.vrbrowser E/GeckoConsole: [JavaScript Error: "TypeError: this.gamepad.hapticActuators[n.actuatorIndex] is undefined" {file: "https://moonrider.xyz/build/build.js" line: 247}]
    pulse@https://moonrider.xyz/build/build.js:247:24084
    onHit@https://moonrider.xyz/build/build.js:16:15640
    checkCollision@https://moonrider.xyz/build/build.js:16:9979
    tick@https://moonrider.xyz/build/build.js:16:9616
    value@https://moonrider.xyz/vendor/aframe-master.min.js:265:11226
    value@https://moonrider.xyz/vendor/aframe-master.min.js:265:11760
    [172]</module.exports/</<@https://moonrider.xyz/vendor/aframe-master.min.js:396:132
    t@https://moonrider.xyz/vendor/aframe-master.min.js:90:3246
```

```
```

</details>

### PR DESCRIPTION
**Pull request by MortimerGoro**
Fixes #2320

### CODE REVIEW

File: app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp [hunk 1]
```diff
@@ -674,6 +674,9 @@ struct DeviceDelegateOculusVR::State {
   uint32_t frameIndex = 0;
   double predictedDisplayTime = 0;
   ovrTracking2 predictedTracking = {};
+  ovrTracking2 discardPredictedTracking = {};
+  uint32_t discardedFrameIndex = 0;
+  int discardCount = 0;
```
Comment (daoshengmu) [inline app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp]: nit: Please unify these variables' naming, `discarded` or `discard`? I would consider to replace `discardFrameIndex` with `discardFrameIndex`.
