### PR TITLE
Make No internet dialog and transport controls not to collide

### LINKED ISSUE #1975: The “Internet Connection Lost” pop up is intermittently displayed behind the on screen controls
**[Affected Versions]:**
- Firefox Reality version 5-32821846 RC1 (58b59be3)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Navigate to any 360 video and enter immersive mode.
2. While in immersive mode terminate the internet connection.
3. Press the trigger button on the controller.
4. Observe the “Internet Connection Lost” pop up.

**[Expected results]:**
- The “Internet Connection Lost” pop up is displayed in front of the on screen controls.

**[Actual results]:**
- The “Internet Connection Lost” pop up is displayed behind the on screen controls.

**[Additional Notes]:**
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1xv8iJQ89cmX_K41CcfwXfthNVk3GN6Bo/view?usp=sharing).

### PR DESCRIPTION
**Pull request by keianhzo**
Fixes #1975 Moving the No Internet dialog in front of the transport controls makes it too close to the user. Instead of that we hide the transport controls when the no internet dialog is displayed. If the user clicks in the video while the no internet dialog is visible, it dismisses it and the transport controls are displayed again.

Also added a listener for the connectivity status so we can eventually listen to that events from any widget.

### CODE REVIEW

File: app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java [hunk 1]
```diff
@@ -145,6 +147,7 @@ public void run() {
     LinkedList<PermissionListener> mPermissionListeners;
     LinkedList<FocusChangeListener> mFocusChangeListeners;
     LinkedList<WorldClickListener> mWorldClickListeners;
+    CopyOnWriteArrayList<Delegate> mConnectivityListeners;
```
Comment (bluemarvin) [inline app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java]: Why use a `CopyOnWriteArrayList`?

Comment (keianhzo) [reply app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java]: Just to avoid concurrent modification issues. We actually talked about auditing all the app listeners and migrate the risky one, this might be low risk though.

File: app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NoInternetWidget.java [hunk 2]
```diff
@@ -11,7 +11,7 @@
 
 import org.mozilla.vrbrowser.R;
 
-public class NoInternetWidget extends UIWidget {
+public class NoInternetWidget extends UIWidget implements WidgetManagerDelegate.WorldClickListener {
```
[the remark this answers is not in the document]
Comment (keianhzo) [reply app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NoInternetWidget.java]: Fixed, now we inherit from UIDialog.
