### PR TITLE
Youtube Web Extension refactor

### LINKED ISSUE #870: 360 YouTube videos do not work when embedded using iframe.
## Hardware
Go
1.1

## Steps to Reproduce
1. Some sites examples with embedded YouTube 360 videos:
http://prosperxr.com/vrportfolio#gameover
https://www.leliomoehr.com/360-vr

2. Click "Watch"

## Current Behavior
360 video plays back with 2D pan controls and will not display correctly in VR modes.

## Expected Behavior
YouTube should play back in unwrapped 360 video that will work with VR video modes.

## Possible Solution
My guess is that the iframe'd YouTube is not seeing customized UA string that plays the video back in unwrapped 360 player.

### LINKED ISSUE #2453: The 360 videos from Youtube are wrongly played in immersive mode when trying to change the video's Settings
**[Affected Versions]:**
- Firefox Reality version 8-33431308 (aee8a16e)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Navigate to a 360 video from Youtube.
2. Click the "Settings" wheel from the video's control bar.
3. Click on one of the options displayed. 

**[Expected results]:**
- The option is selected or the sub-menus of the options are displayed.

**[Actual results]:**
- The video is played in immersive mode.

**[Notes]:**
- I was not able to reproduce this issue on the Vimeo website.
- Tracked by #1760.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1pDv20fPZ-dI97jiw8wx8rr1A6o8oc0Rs).

### LINKED ISSUE #2457: youtube videos are defaulting to low-res
From @larsbergstrom 12/11/19 : YouTube videos are playing at 1440p don't adapt even when higher resolutions are available. 

Expected: We should be defaulting to the highest available quality via our custom YouTube extension.

@bluemarvin suggested we check the labels we're using for quality (`prefs.qualityLabels`)

needed by #1760

### LINKED ISSUE #2459: Some of the YouTube controls/buttons flicker when they are hovered in a window size equal or smaller than 1x
**[Affected Versions]:**
- Firefox Reality version 8-33452219 (bfee54ee)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- The window size is set to 1x.

**[Steps to reproduce]:**
1. Navigate to any video and play the video. (if immersive mode is entered exit)
2. Using the controller hover the video controls. (play, Next, volume, CC, …)
3. Observe the behavior.

**[Expected results]:**
- The video controls appear and are actionable.

**[Actual results]:**
- The video controls flicker.

**[Notes]:**
- The flicker can be seen on the “Upload” button tooltip as well, when the button is hovered.
- The flicker can be seen on the “Watch Later” button as well, when the button is hovered.
- The issue is not reproducible on a window size bigger than 1x size.
- The video controls flicker is much more visible on the HTC device.
- Needed by #1760.
- Attached a screen recording of the issue on the HTC device [here](https://drive.google.com/open?id=1HGaLgyqNHfFGtWNthpegR5ZTw6ocIUrl).
- Attached a screen recording of the issue on the Oculus device [here](https://drive.google.com/open?id=1COaRdmn1waIvgBWxZNFsbS1WMoU7fiSs).

### LINKED ISSUE #2463: The Youtube's progress bar is wrongly actionable outside its area
**[Affected Versions]:**
- Firefox Reality version 8-33452219 (bfee54ee)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Navigate to a Youtube video.
2. Click outside the video's progress bar boundaries.
3. Observe the behavior.

**[Expected results]:**
- The progress bar is not actionable.

**[Actual results]:**
- The progress bar is actionable.

**[Notes]:**
- The actionable area of the progress bar is also affecting the videos controls buttons displayed under the progress bar.
- Needed by #1760.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=13sYSZC0Aw3RYDdsyVmbqiq_LQztXHy3D).

### PR DESCRIPTION
**Pull request by MortimerGoro**
- Fixes unneeded horizontal scrolling
- Fixes #2453
- Fixes #2463
- Fixes #2457 (I'll handle disabling high res as a follow-up in devices such as Oculus Go)
- Fixes/Improves #2016 (I fixed potential duplicated selectQuality calls)
- Fixes #870
- Fixes #2459

### CODE REVIEW

File: app/src/main/assets/web_extensions/webcompat_youtube/background.js [hunk 1]
```diff
@@ -10,24 +11,44 @@ const targetUrls = [
...
+ * Override UA. This is required to get the equirectangular video formats from Youtube.
+ * Otherwise youtube uses custom 360 controls.
+ */
+function overrideUA(req) {
+    for (const header of req.requestHeaders) {
+        if (header.name.toLowerCase() === "user-agent") {
+            header.value = CUSTOM_USER_AGENT;
+        }
+    }
+    return { requestHeaders: req.requestHeaders };
```
Comment (bluemarvin) [inline app/src/main/assets/web_extensions/webcompat_youtube/background.js]: Is this to work around an issue with GV UA override?

Comment (MortimerGoro) [reply app/src/main/assets/web_extensions/webcompat_youtube/background.js]: yes, it's the only way I found to apply the UA in youtube iframes

Comment (bluemarvin) [reply app/src/main/assets/web_extensions/webcompat_youtube/background.js]: Would you file a GV issue on bugzilla outlining the problems you encountered. It might end up being that webext is the preferred way to solve the problem but would like it to at least be on the teams radar.

**Comment by MortimerGoro** [comment]
Fixes #2134
