### PR TITLE
Pinyin keyboard fixes

### LINKED ISSUE #1253: minor changes to Pinyin keyboard
Minor updates based on feedback. Latest spec is here:
https://trello.com/c/GeLVSIig/119-uis-27-chinese-keyboard-pinyin

Waiting for one more piece of feedback and then we'll be at final design.

### PR DESCRIPTION
**Pull request by MortimerGoro**
- Add correct pinyin punctuation autocompletion (pinyin comma and dot)
- Improve autocompletion view layouts 

Fixes #1253

### CODE REVIEW

File: app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/ChinesePinyinKeyboard.java [hunk 1]
```diff
@@ -50,7 +50,9 @@ public CandidatesResult getCandidates(String aComposingText) {
         }
 
         // Autocomplete when space is clicked
```
Comment (daoshengmu) [inline app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/ChinesePinyinKeyboard.java]: nit: We should change this comment because we also do the same things on comma and period.

**Comment by MortimerGoro** [comment]
@daoshengmu It's based on the latest final design in #1253. The changes are:

- Add the Chinese comma
- Add the Chinese period
- Add the Chinese long sound symbol
- Updated hover styles for autocompletion items
- Improve autocomplete items size math

I'm missing any extra change? Emojies are not ready yet

File: app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/ChinesePinyinKeyboard.java (hunk 1 above)
Comment (MortimerGoro) [reply app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/ChinesePinyinKeyboard.java]: Fixed

File: app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/ChinesePinyinKeyboard.java [hunk 2]
```diff
@@ -49,7 +49,7 @@ public CandidatesResult getCandidates(String aComposingText) {
             return null;
         }
 
-        // Autocomplete when space is clicked
+        // Autocomplete when special characters are clicked
         boolean autocomponse = aComposingText.endsWith(" ")
                                || aComposingText.endsWith("，")
                                || aComposingText.endsWith("。");
```
Comment (daoshengmu) [inline app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/ChinesePinyinKeyboard.java]: It seems like `!`, `?`, and long sound symbol also need to be added to this rule.

**Comment by daoshengmu** [comment]
org mozilla vrbrowser-20190530-154203
I was trying to type `ko`, and the autocomplete item layout seem to go wrong as above.

**Comment by MortimerGoro** [comment]
I've fixed the extra autocompletion characters and the layout issue.

> The hover style is not the same with the design document. It supposes to be Tangerine color.

I see the tangerine color is not used for all the hovers but only for the  `selected option by spacebar`. Right know the spacebar always selects the first autocompletion option. Is the design assuming we can select another one with spacebar? how is it selected? cc @thenadj @jvonitter could you clarify this?

**Comment by thenadj** [comment]
@MortimerGoro There is no autocomplete navigation for the Pinyin keyboard. The spacebar ONLY selects the first option in the autocomplete. To choose other options, the user has to click characters with their controller. The specs at the bottom of the document are to show different interaction states.

Ping me in Slack if it doesn't make sense.

**Comment by MortimerGoro** [comment]
@thenadj @daoshengmu since there is no autocomplete navigation, should we use the Tangerine color always on the fist autocomplete option? If we don't want the color the PR is ready to merge. If we want the color I'll update the PR

**Comment by daoshengmu** [comment]
It looks good to me now. We just need to know if we want to use the Tangerine color on the fist autocomplete option

**Comment by thenadj** [comment]
Yes, we want to use the tangerine color on the first autocomplete item. It also helps with consistency of other keyboards like Japanese that have this color too.

**Comment by MortimerGoro** [comment]
I added the tangerine color
