### PR TITLE
Deactivate current session when receiving a new tab

### LINKED ISSUE #2281: The video/audio from the previous tab is wrongly played in the background after receiving a tab
**[Affected Versions]:**
- Firefox Reality 7 RC1 (b772e6d7) build.

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- Make sure that the FxA account is logged on the VR device and also on a second device.
- The volume of the VR device is turned on.

**[Steps to reproduce]:**
1. Open a normal video and play it.
2. Send a tab from a second device to the VR device.
3. Click the "Tabs View" button from the tray menu.
4. Listen if the video/audio from the previous tab is still playing. 

**[Expected results]:**
- The video/audio is paused.

**[Actual results]:**
- The video/audio is playing in the background.

**[Notes]:**
- This issue is also reproducible after the device exits sleep mode.
- The video/audio continues to play in the background until it's paused from the tab that was initially played.
- This issue is not reproducible if the video is played in theater or immersive mode.
- This issue is not reproducible if the tabs are switched while a video is playing. 
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1_6thaxVuhgBY_UC2_pu3xFmD3W1DYTvj)

### PR DESCRIPTION
**Pull request by keianhzo**
Fixes #2281 Deactivate current session when receiving a new tab

### CODE REVIEW

File: app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java [hunk 1]
```diff
@@ -1245,6 +1245,11 @@ public void onTabsClose(ArrayList<Session> aTabs) {
     @Override
     public void onTabsReceived(@NotNull List<TabData> aTabs) {
         WindowWidget targetWindow = mFocusedWindow;
+
+        if (!aTabs.isEmpty()) {
+            targetWindow.getSession().setActive(false);
+        }
+
```
Comment (bluemarvin) [inline app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java]: I think if we are fullscreen this will just set the fullscreen Session to inactive?

Comment (MortimerGoro) [reply app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java]: yes, fullscreen needs to be checked. You can move the setActive false to before this line https://github.com/MozillaReality/FirefoxReality/blob/2667446b82846e279c01628c5383109cfc4221de/app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java#L1265

Comment (keianhzo) [reply app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java]: Fixed
