### PR TITLE
Force view redraw when showing the awesome bar

### LINKED ISSUE #2012: Pages visted while using private browsing can be shown as a sugestion in the awesome bar.
## Configuration

Firefox Reality version: 6
Firefox Reality build ID: f4384ca149463e6a64351245827944d87bb8678d

Hardware: Quest

## Steps to Reproduce

1. Clear history.
2. Enter private browsing
3. Visit a web site
4. leave private browsing
5. click on the URL bar and press `.` on the keyboard

## Current Behavior

The URL visited in private browsing is suggested in the awesome bar suggestion menu.
## Expected Behavior

URLs visited only in private browsing should not be used as suggestions in the pop up bar

### PR DESCRIPTION
**Pull request by keianhzo**
Closes #2012

### CODE REVIEW

**Comment by bluemarvin** [comment]
This doesn't compile with the tabs now in master.
```
        if (!mSessionStack.isPrivateMode()) {
             ^
  symbol:   variable mSessionStack
  location: class WindowWidget
```

File: app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java [hunk 1]
```diff
@@ -1392,8 +1392,10 @@ public void onLocationChange(@NonNull GeckoSession session, @Nullable String url
 
     @Override
     public void onHistoryStateChange(@NonNull GeckoSession geckoSession, @NonNull HistoryList historyList) {
-        for (HistoryItem item : historyList) {
-            SessionStore.get().getHistoryStore().recordObservation(item.getUri(), new PageObservation(item.getTitle()));
+        if (!mSessionStack.isPrivateMode()) {
```
Comment (bluemarvin) [inline app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java]: Needs to be `mSession` now.
