### PR TITLE
Correct the keyboard layout when showing from the focus view.

### LINKED ISSUE #3640: [Keyboard: Thai] The keyboard is cut off at the bottom when reopening the keyboard after dismissing the symbol keyboard
**[Affected Versions]:**
- Firefox Reality version 11 RC4 (c28ddb2e)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Pico G2 4K - Android 8.1.0
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- Make sure the Thai keyboard is selected.

**[Steps to reproduce]:**
1. Click inside the awesomebar.
2. Switch to the symbol keyboard.
3. Dismiss the keyboard.
4. Click inside the awesomebar and observe the keyboard.

**[Expected results]:**
- The Thai keyboard is displayed correctly.

**[Actual results]:**
- The Thai keyboard is cut off at the bottom of the keyboard.

**[Notes]:**
- The keyboard remains cut off until the language is changed.
- Changing the keyboard is difficult by the fact that only a small portion of the button is visible.
- The issue could not be verified on HTC devices because of #3638.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1jJvlteRbcYFNtjndA1AwbWNkinWcbJGB/view?usp=sharing).

### PR DESCRIPTION
**Pull request by daoshengmu**
Fixes #3640.

### CODE REVIEW

File: app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java [hunk 1]
```diff
@@ -972,31 +973,42 @@ private void handleDone() {
         }
     }
 
-    private void handleModeChange() {
-        Keyboard current = mKeyboardView.getKeyboard();
+    private void handleShowKeyboard(Keyboard aKeyboard) {
         Keyboard alphabetic = mCurrentKeyboard.getAlphabeticKeyboard();
         Keyboard alphabetiCap = mCurrentKeyboard.getAlphabeticCapKeyboard();
```
Comment (bluemarvin) [inline app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java:978]: nit: Looks like `alphabetiCap` should be `alphabeticCap`. Can be addressed in follow up since it is preexisting.

**Comment by bluemarvin** [comment]
Let's land this so I can create an rc5 and address any new issues in follow ups.
