### PR TITLE
Fixes #750 Wrong icon/look with new Resize Mode icons

### LINKED ISSUE #750: Wrong icon/look with new Resize Mode icons (and in Private Browsing mode)
## Hardware
Oculus Go
eaa4fc5

## Steps to Reproduce
1. Press the Resize Mode icon (below the URL bar in the bottom-right corner).
2. Notice the new style of the Resize Mode.
3. Press the Private Browsing icon in the Tray.
4. Notice the last icon (the checkmark icon) is curved in non-Private Browsing.

## Current Behavior
in eaa4fc5:
image
image

## Expected Behavior
in `1.0.1`:
image
image

### PR DESCRIPTION
**Pull request by keianhzo**
Fixes #750 Wrong icon/look with new Resize Mode icons

### CODE REVIEW

File: app/src/common/shared/org/mozilla/vrbrowser/ui/views/UITextButton.java [hunk 1]
```diff
@@ -55,14 +91,60 @@ protected void drawableStateChanged() {
...
+        } else {
+            setNormal();
+            mState = State.NORMAL;
+        }
+    }
+
+    public void setActiveMode(boolean isActive) {
+        if (isActive) {
+            setActive();
+            mState = State.ACTIVE;
```
Comment (cvan) [inline app/src/common/shared/org/mozilla/vrbrowser/ui/views/UITextButton.java]: would it make more sense for the `mState = …` assignments to happen inside `setActive` and `setNormal`?

Comment (keianhzo) [reply app/src/common/shared/org/mozilla/vrbrowser/ui/views/UITextButton.java]: Yep, that makes more sense. Fixed.
