### PR TITLE
Pause media when the app goes to background.

### LINKED ISSUE #429: stop audio/video when backgrounded.
## Steps to Reproduce

1. Watch video on CNN

## Current Behavior

CNN.com video just keep playing until FxR is killed.

## Expected Behavior

CNN.com should stop playing when backgrounded or page exited

### PR DESCRIPTION
**Pull request by MortimerGoro**
Fixes #429.

Gecko side PR: https://phabricator.services.mozilla.com/D4472
We need to wait for it to land this

### CODE REVIEW

File: app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java [hunk 1]
```diff
@@ -176,11 +177,19 @@ protected void onStop() {
     @Override
     protected void onPause() {
         mAudioEngine.pauseEngine();
+        GeckoSession current = SessionStore.get().getCurrentSession();
```
Comment (bluemarvin) [inline app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java]: I think SessionStore.setActive() would be better since in the future we will probably have more than just one active GeckoSession. Also, this potentially won't work if there are multiple sessions on the store stack from a onCreateNewSession call.

**Comment by bluemarvin** [comment]
We will need to remember to bump the GV version number once the GV dependent bug lands before we can land this PR.

**Comment by bluemarvin** [comment]
@MortimerGoro I have upgraded the pinned GV version and tested that this patch compiles against it. Once you address the review comments it's ready to land 🙂

**Comment by MortimerGoro** [comment]
PR updated
