### PR TITLE
Fixes #3321 Fixes #3320 Fixes #3317 Downloads list improvements

### LINKED ISSUE #3317: The Downloads library is wrongly scrolled down when files are sorted
**[Affected Versions]:**
- Firefox Reality version 10 RC4 (2999129).

**[Affected Platforms]:**
- Pico Neo 2 - Android - 8.1.0
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the app is opened.
- Have an extended list view for the Downloads library (more than 10 downloads).

**[Steps to reproduce]:**
1. Click the Downloads button from the tray.
2. Click the Sort By button.
3. Select an sort by option and observe the behavior.

**[Expected results]:**
- The page is scrolled up to the first item.

**[Actual results]:**
- The page is scrolled down.

**[Notes]:**
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1lSOxClnzb4MYEQLHT5Vbv6qG4iSysYbH).

### LINKED ISSUE #3320: The Downloads library is wrongly scrolled and files are switched when downloading multiple files at the same time
**[Affected Versions]:**
- Firefox Reality version 10 RC4 (2999129).

**[Affected Platforms]:**
- Pico Neo 2 - Android - 8.1.0
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**
1. Start downloading multiple files (~10) at the same time.
2. Click the Downloads button from the tray.
3. Observe the list.

**[Expected results]:**
- The files and page remain in the same position so that the download process can be followed.

**[Actual results]:**
- The files are switched and the page is scrolled making the download process hard to follow.

**[Notes]:**
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1ykHDQhP16bEAfrvPfmXtyTR8ohkRnOP5).

### LINKED ISSUE #3321: The Downloads list is wrongly resorted after a quit/resume
**[Affected Versions]:**
- Firefox Reality version 10 RC4 (2999129).

**[Affected Platforms]:**
- Pico Neo 2 - Android - 8.1.0
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the app is opened.
- Have multiple downloaded files in the list.

**[Steps to reproduce]:**
1. Click the Downloads button from the tray.
2. Click the "Sort By" button and choose an option (ex "Smallest".)
3. Quit and resume the app.
4. Observe if the sorted option is kept.

**[Expected results]:**
- The files are sorted in the last chosen option.

**[Actual results]:**
- The files are resorted.

**[Notes]:**
- On HTC and Pico devices the issue is reproducible only after the app is forced stopped.
- As a side effect of this issue if there are a lot of downloads available, after resume the Downloads page will take a few seconds to load.
- It seems like the files are not resorted in a specific order.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=12swgok-r417OKjj0IM7WrHsfye5xQVNM).

### PR DESCRIPTION
**Pull request by keianhzo**
Fixes #3321 Fixes #3320 Fixes #3317 Fixes the issues with sorting when there are items with the same size and name. Also fixes sorting restoration upon restart  and scrolling when sorting is changed.

### CODE REVIEW

File: app/src/common/shared/org/mozilla/vrbrowser/ui/views/library/DownloadsView.java [hunk 1]
```diff
@@ -352,14 +334,67 @@ protected void showSortingContextMenu(@NonNull View view) {
...
+    private Comparator<Download> mAZFileNameComparator = (o1, o2) -> {
+        int nameDiff = o1.getFilename().compareTo(o2.getFilename());
+        if (nameDiff == 0) {
+            return  mDownloadIdComparator.compare(o1, o2);
+
+        } else {
+            return nameDiff;
+        }
+    };
+    private Comparator<Download> mZAFilenameComparator = (o1, o2) -> {
```
Comment (bluemarvin) [inline app/src/common/shared/org/mozilla/vrbrowser/ui/views/library/DownloadsView.java:369]: Nit: `mAZFileNameComparator` vs `mZAFilenameComparator` `Name` is only capitalized in one of the names. Can address in a follow up.
