### PR TITLE
Avoid duplicated  GeckoSession setActive calls

### LINKED ISSUE #2372: [Intermittent] A new FxA account can’t be verified
**[Affected Versions]:**
- Firefox Reality version 7 RC3 (7b66fb14)
- Firefox Reality version 7-33291756 (66da79cc)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- Make sure an FxA account is NOT logged in.

**[Steps to reproduce]:**
1. Go to the Settings menu and click the “Sign Into Account” card.
2. Fill in a never before used valid email address and click the “Continue” button.
3. Fill in the required fields and continue.
4. Enter the 6 digit verification code sent to the email address used.
5. Click the “Verify” button and observe the behavior.

**[Expected results]:**
- The account is verified and the Settings menu is redisplayed.

**[Actual results]:**
- Nothing happens.

**[Notes]:**
- At the next sign in attempt the user can sign in using this account like it was verified.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1eiy5z26U4tEx7bj76tjrlNffYsX11-FI).
- Attached the logcat file of the issue [here](https://drive.google.com/open?id=1Iy2E0dMd9yRaAjhi8OQdDF4VgTqQetlw).

### LINKED ISSUE #2373: [Intermittent] An FxA user can’t sign in at first attempt
**[Affected Versions]:**
- Firefox Reality version 7 RC3 (7b66fb14)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- Make sure that the app is freshly installed on the device. 
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Go to the Settings menu and click the “Sign Into Account” card.
2. Fill in a valid email address of an FxA account.
3. Click the “Continue” button and observe the behavior.

**[Expected results]:**
- The user can sign in using a valid email address.

**[Actual results]:**
- Nothing happens.

**[Notes]:**
- The issue is also reproducible if using a never before used valid email address to create an account.
- At the next sign in attempt the user can sign in normally.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1cVsNUV3Bot9lFAqQo86yKowI7JL7dWZs).
- Attached the logcat file of the issue [here](https://drive.google.com/open?id=1ICdeqtsh1EtdfqJVQliFekzEW2J0__J4).

### PR DESCRIPTION
**Pull request by keianhzo**
Fixes #2373 Fixes #2372 We were calling setActive twice when pausing/resuming the app and that seems to mess up GV state and triggered a JS error in the FxA login page: `throw new Error('submit already in progress');`

This could affect any other website, not only FxA.

STRs:
- SignIn using a non existing account (you can just add a `+n` to an existing account: user+n@mozilla.com)
- Fill the form and continue
- An email with the code should be received in that account
- When checking the code, click on the home button to pause the activity (otherwise it works)
- Resume the app again, put the code and click on Verify

Result: The Verify button doesn't work

### CODE REVIEW

File: app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java [hunk 1]
```diff
@@ -401,9 +401,7 @@ protected void onPause() {
             exitImmersiveSync();
         }
         mAudioEngine.pauseEngine();
-
-        mWindows.onPause();
```
Comment (MortimerGoro) [inline app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java]: - `saveState()` is run inside windows.onPause(), are we missing that call now?

Comment (MortimerGoro) [reply app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java]: I'm also concerned that if a window is hidden the mWindow.onPause not getting called from the loop because it may have been removed from the mWidgets container:
   ```
     for (Widget widget: mWidgets.values()) {
            widget.onPause();
        }
```

Comment (keianhzo) [reply app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java]: Updated so we call `saveState`.

The onPause/onResume calls are also called for hidden widgets so they should be called for any existing window.
