### PR TITLE
Save autoplay state. Fixes #1781

### LINKED ISSUE #1781: The "Autoplay Media" setting is wrongly reset to the default value after update
**[Affected Versions]:**
- Firefox Reality 1.4-32481747 (RC3)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- Have the production version of Firefox Reality 1.3 installed.
- Have the latest 1.4-32481747 (RC3) build downloaded.
- The sideloading is set up following the steps from: [link](https://github.com/MozillaReality/FirefoxReality/wiki/Developer-workflow:-install-ADB)
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**
1. Open the FxR 1.3 app.
2. Click the "Settings" (gear) button from the menu tray.
3. Click the "Privacy & Security" card and turn the "Autoplay Media" setting on.
4. Press the oculus/vive button on the controller and "Quit" the app.
5. Sideload the following command to update the app: "adb install -r <path to the 1.4-32481747 (RC3) build from prerequisites>".
6. Open the FxR app again and click the "Settings" (gear) button from the menu tray.
7. Click the "Display" card and observe the "Autoplay Media" setting.

**[Expected results]:**
- The "Autoplay Media" setting is still turned on after the update.

**[Actual results]:**
- The "Autoplay Media" setting is reset to its default value, off.

**[Notes]:**
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1x68gafgeZWIoKWdIh3grDyCkDAoDomY1/view?usp=sharing).

### PR DESCRIPTION
**Pull request by bluemarvin**

### CODE REVIEW

File: app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStore.java [hunk 1]
```diff
@@ -218,6 +219,7 @@ public void setAutoplayEnabled(final boolean enabled) {
             mRuntime.getSettings().setAutoplayDefault(enabled ?
                     GeckoRuntimeSettings.AUTOPLAY_DEFAULT_ALLOWED :
                     GeckoRuntimeSettings.AUTOPLAY_DEFAULT_BLOCKED);
+            SettingsStore.getInstance(mContext).setAutoplayEnabled(enabled);
```
Comment (MortimerGoro) [inline app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStore.java]: For consistency we should call this method in: `DisplayOptionsView.setAutoplay`
