### PR TITLE
Avoid the FxA crash when reloading the success page after logout

### LINKED ISSUE #2201: The app is closed and crashed after signing out from the FxA account and refreshing the "You are now Connected" confirmation page
**[Affected Versions]:**
- Firefox Reality Firefox Reality 6-33112229 RC4 (f2e90af0) build.

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- Have a valid FxA account.
- You are not connected to the FxA account.

**[Steps to reproduce]:**
1. Click the "Sign into Account" card from settings.
2. Log in using the account from prerequisites.
3. Click the "Sign Out" button from the "Manage Account" prompt displayed.
4. Dismiss the prompts displayed.
5. Refresh the "You are now Connected" confirmation page from the browser and observe the behavior.

**[Expected results]:**
- The "Sign in" FxA page is displayed.

**[Actual results]:**
- The app is closed and the crash report is displayed after reopening the app.

**[Notes]:**
- This issue is not reproducible if the "You are now Connected" confirmation page is refreshed while logged in.
- On Firefox Desktop the "You are now Connected" confirmation page is automatically refreshed after signing out from the FxA account and the "Sign In" page is displayed instead.
- Attached are a screen recording along with the logcat and the crash report of the issue: 
	- Screen recording: [link](https://drive.google.com/open?id=1-qeiCmi7TXJhdFnEoxf7tJWzefGS9vLy)
	- Logcat: [link](https://drive.google.com/open?id=1fViUhVJhzLsC4HYt2y6_TIc0Vq0ugFkj)
	- Crash report: [link](https://crash-stats.mozilla.com/report/index/bp-a76b7e4b-2e8d-4e82-899b-9c2db0191108)

### PR DESCRIPTION
**Pull request by keianhzo**
Fixes #2201 Crash related to this AS issue: https://github.com/mozilla/application-services/issues/2131

To avoid the issue we close the FxA login tab and load the login scuess URL after a successful login.

### CODE REVIEW

File: app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java [hunk 1]
```diff
@@ -889,6 +891,10 @@ public void onLoggedOut() {
 
         @Override
         public void onAuthenticated(@NotNull OAuthAccount oAuthAccount, @NotNull AuthType authType) {
+            Session session = mFocusedWindow.getSession();
+            addTab(mFocusedWindow, mAccounts.getConnectionSuccessURL());
+            onTabsClose(new ArrayList<>(Collections.singletonList(session)));
```
Comment (MortimerGoro) [inline app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java]: you need to add `SessionStore.get().setActiveSession() `

Comment (MortimerGoro) [reply app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java]: nevermind, t's added in `addTab`
