### PR TITLE
Fixes #3604 Exclude FxA login urls from history

### LINKED ISSUE #3604: [FxA] The app crashes if the account is reconnected from the previous "Sign in" page
**[Affected Versions]:**
- Firefox Reality version 11 RC2 (5fd1bfd).

**[Affected Platforms]:** 
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- Have a valid FxA account.

**[Steps to reproduce]:**
1. Log into the FxA account.
2. Sign out from the FxA account.
3. From History open the "Log in" page.
4. Enter the password and click the "Log In" button.
5. Observe the behavior.

**[Expected results]:**
- An error is displayed informing that the login can't be perform through this page.

**[Actual results]:**
- The app crashes.

**[Notes]:**
- If Step 2 is not performed, the Log In page remains in a working state.
- Attached is a screen recording, logcat and the crash report of the issue:
	- Screen Recording: [link](https://drive.google.com/file/d/18THZ0EDlKyNpHqOFXWgp8OMg6rjz_pDR/view?usp=sharing).
	- Crash Report: [link](https://crash-stats.mozilla.org/report/index/d76fcbde-97ec-4453-8a08-90a130200702).
	- Logcat: [link](https://drive.google.com/file/d/1X-jxnCvbkuI2VcXWG_51RtSi3nOZdKrr/view?usp=sharing).

### PR DESCRIPTION
**Pull request by keianhzo**
Fixes #3604 Exclude FxA login urls from history

### CODE REVIEW

File: app/src/common/shared/org/mozilla/vrbrowser/browser/HistoryStore.kt [hunk 1]
```diff
@@ -17,13 +17,19 @@ import mozilla.components.support.base.log.logger.Logger
...
 class HistoryStore constructor(val context: Context) {
 
     private val LOGTAG = SystemUtils.createLogtag(HistoryStore::class.java)
 
     private var listeners = ArrayList<HistoryListener>()
     private var storage = (context.applicationContext as VRBrowserApplication).places.history
+    private val blocklist = Stream.of(
+            "https://accounts.firefox.com/authorization",
+            "https://accounts.firefox.com/oauth"
+    ).collect(Collectors.toList())
```
Comment (bluemarvin) [inline app/src/common/shared/org/mozilla/vrbrowser/browser/HistoryStore.kt:32]: Can we keep this list in one place?

Comment (keianhzo) [reply app/src/common/shared/org/mozilla/vrbrowser/browser/HistoryStore.kt]: Done

**Comment by bluemarvin** [comment]
The tc task finished. Not sure why github didn't update status. Lets land it.
