### PR TITLE
Dispatch fullscreen change notification on recreated sessions

### LINKED ISSUE #3183: If the content process crashes or is killed while in fullscreen and or immersive mode, the windows are left in a bad state.
## Configuration

Firefox Reality version: 10
Firefox Reality build ID: 58ba8ea588b19d9295eb245f92d8e6e91eec5c2c

Hardware: All

## Steps to Reproduce

1. Open 360 video and enter immersive mode.
2. Use adb to kill the content process 

## Current Behavior

The WindowWidgets still behave as if they are in fullscreen mode while the recreated GeckoSession is not.

## Expected Behavior

All the windows are restored to their default mode (not in fullscreen or immersive mode).

### PR DESCRIPTION
**Pull request by MortimerGoro**
Fixes #3183

### CODE REVIEW

File: app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java [hunk 1]
```diff
@@ -917,8 +917,12 @@ public void saveBeforeFullscreenPlacement() {
     }
 
     public void restoreBeforeFullscreenPlacement() {
+        // We need to process composited`` separately to handle GV content process onCrash/onKill.
```
Comment (bluemarvin) [inline app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java:920]: Looks like some extra back ticks got into the comment.
