### PR TITLE
Switch environment from developer panel

### LINKED ISSUE #171: Set up correct lighting for meadow environment
The browser widget lighting doesn't feel good in the meadow environment. We need to adjust it.

Also sometimes it looked like the direcional light changed while the user orientation changes (it was very easy to see in the first meadow model without colors). Check if this is still a bug

### LINKED ISSUE #417: Transition to skyboxes for environments
After discussions with @thenadj, @avrignaud, @bluemarvin, @MortimerGoro, and @keianhzo, we have  decided to transition from the use of modeled environments back to a skybox. This will allow us to address some rendering issues (e.g., #171 providing additional control over the environment) and reduce the engineering work to continue to tweak and optimize the model loader and renderer through the end of this calendar year (2018).

It will also afford us with some great places to experiment with end-user customization, speed up the workflow for designers to iterate with new designs (just push a skybox over via adb!), and for web content to make customizations available (see https://github.com/immersive-web/proposals/issues/23).

### LINKED ISSUE #464: Add a dev panel option to choose between meadow/mushrooms env
## Hardware
All

## Current Behavior
We have two environments meadows/mushrooms but only one is visible.

## Expected Behavior
The user should be able to switch between both

## Possible Solution
Add a radio button to select the environments

## Error Logs and Stack Traces

<details open>

```
```

</details>

### PR DESCRIPTION
**Pull request by keianhzo**
Fixes #417, Fixes #464, Fixes #171  Added developer panel option to switch between meadow/cave skyboxes

### CODE REVIEW

File: app/src/common/shared/org/mozilla/vrbrowser/SettingsStore.java [hunk 1]
```diff
@@ -231,4 +232,15 @@ public void setMaxWindowHeight(int aMaxWindowHeight) {
         editor.commit();
     }
 
+    public String getEnvironment() {
+        return mPrefs.getString(
```
Comment (bluemarvin) [inline app/src/common/shared/org/mozilla/vrbrowser/SettingsStore.java]: Are pref functions thread safe or do we need to synchronize getEnvironment and setEnvironment since they are called in both UI thread and GL thread?

Comment (bluemarvin) [reply app/src/common/shared/org/mozilla/vrbrowser/SettingsStore.java]: Okay, I see they are.
