### PR TITLE
Fixed showing microphone icon when there is text in the URL

### LINKED ISSUE #514: Microphone icon shows when clear icon should show in URL bar
## Steps to Reproduce

1. Enter URL into URL bar
2. Clear it by pressing the `x` button in the URL bar
3. The `x` is replaced with the microphone button.
4) Press the microphone button and do a voice search.

## Current Behavior

Even thought there is now a URL in the URL bar and it has focus, the microphone button is still visible.

## Expected Behavior

The clearing `x` button should be visible.

## Possible Solution

Make sure the button state is switched when there is text in URL bar and it has focus.

### PR DESCRIPTION
**Pull request by keianhzo**
Fixes #514 Fixed showing microphone icon when there is text in the URL after a voice search

### CODE REVIEW

File: app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationURLBar.java [hunk 1]
```diff
@@ -73,8 +73,8 @@ public boolean onEditorAction(TextView aTextView, int actionId, KeyEvent event)
         mURL.setOnFocusChangeListener(new OnFocusChangeListener() {
             @Override
             public void onFocusChange(View view, boolean b) {
-                if (b && mURL.getText().length() > 0) {
-                    showVoiceSearch(false);
+                if (b) {
```
Comment (bluemarvin) [inline app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationURLBar.java]: In a follow up, we should rename that `b` variable to something else.
