### PR TITLE
Fix exit fullscreen viewport scaling issues

### LINKED ISSUE #833: <video>s gets increasingly smaller after entering and exiting fullscreen VR videos (reproducible on any site, including YouTube)
STR:

1) Load https://www.youtube.com/watch?v=sPyAQQklc1s
2) Enter Fullscreen
3) Enter 360 video projection
4) Exit video projection
5) Exit fullscreen
6) See Repeat step 2

### PR DESCRIPTION
**Pull request by MortimerGoro**
Fixes #833

### CODE REVIEW

File: app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java [hunk 1]
```diff
@@ -416,6 +416,14 @@ private void exitFullScreenMode() {
             return;
         }
 
+        // We need to add a delay for the exitFullScreen() call to solve some viewport scaling issues,
+        // See https://github.com/MozillaReality/FirefoxReality/issues/833 for more info.
+        getHandler().postDelayed(() -> {
+            if (SessionStore.get().isInFullScreen()) {
+                SessionStore.get().exitFullScreen();
+            }
+        }, 50);
```
Comment (cvan) [inline app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java]: this solves the issue for now. shall we keep #833 open for a more proper investigation + solution after 1.1?
