### PR TITLE
Fixes #2829 Hide all notifications when clicking on tray actions

### LINKED ISSUE #2829: The “Pop-Up Blocked” notification wrongly remains displayed in the Bookmark/History View
**[Affected Versions]:**
- Firefox Reality version 9 RC2 (37ac4cbd)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Navigate to the following website: "http://popuptest.com/”
2. Click on a pop-up technique.
3. After the “Pop-Up Blocked” notification appears, click the Bookmark/History button in the menu tray.
4. Observe the “Pop-Up Blocked” notification.

**[Expected results]:**
- The “Pop-Up Blocked” notification is dismissed.

**[Actual results]:**
- The “Pop-Up Blocked” notification remains displayed.

**[Notes]:**
- The issue is not reproducible in production, FxR V8.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1hwwYUM9Wi1CcC0uxrTidBy0zlD5V2k6O).

### PR DESCRIPTION
**Pull request by keianhzo**
Fixes #2829 Hide all notifications when clicking on tray actions. Also avoid concurrent modifications of the notifications map

### CODE REVIEW

File: app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NotificationManager.java [hunk 1]
```diff
@@ -14,15 +14,15 @@
...
 import java.util.Iterator;
 import java.util.Map;
+import java.util.concurrent.ConcurrentHashMap;
 
 public class NotificationManager {
 
     private static final int DEFAULT_DURATION = 3000;
 
-    private static HashMap<Integer, NotificationData> mData = new HashMap<>();
+    private static ConcurrentHashMap<Integer, NotificationData> mData = new ConcurrentHashMap<>();
```
Comment (bluemarvin) [inline app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NotificationManager.java]: Why the need for a `ConcurrentHashMap`?

Comment (keianhzo) [reply app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NotificationManager.java]: We don't really. We were iterating over the Hashmap and then calling `hide` which removed the items using `remove` on the Hashmap which causes a `concurrentmodificationexception`. So it was a lazy way of reusing that method. I've pushed a PR to avoid using the `ConcurrentHashMap`: https://github.com/MozillaReality/FirefoxReality/pull/2847
