### PR TITLE
Check app button when in immersive mode. Fixes #275

### LINKED ISSUE #275: App Button fails to exit immersive mode
Hardware: GVR and Wave
Steps to Reproduce:
1) Enter Immersive mode
2) Press App Button
Actual Behavior: Nothing happens
Expected Behavior: Immersive mode is exited.
Recommendation: The application is not checking the app button for GVR and Wave when in immersive mode.

### PR DESCRIPTION
**Pull request by bluemarvin**

### CODE REVIEW

File: app/src/main/cpp/BrowserWorld.cpp [hunk 1]
```diff
@@ -178,11 +178,26 @@ struct BrowserWorld::State {
     fadeBlitter = FadeBlitter::Create(create);
   }
 
+  void CheckBackButton();
   void UpdateControllers(bool& aRelayoutWidgets);
   WidgetPtr GetWidget(int32_t aHandle) const;
   WidgetPtr FindWidget(const std::function<bool(const WidgetPtr&)>& aCondition) const;
 };
 
+void
```
Comment (MortimerGoro) [inline app/src/main/cpp/BrowserWorld.cpp]: Could we reuse CheckBackButton() function also from UpdateControllers()?

Comment (MortimerGoro) [reply app/src/main/cpp/BrowserWorld.cpp]: controller.lastButtonState complicated to do that
