### PR TITLE
Fixes #3228 Send only http/https tabs

### LINKED ISSUE #3228: The downloaded files can wrongly be sent as tabs
**[Affected Versions]:**
- Firefox Reality version 10 RC1 (6db2f60a).

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Click the Downloads button from the tray.
2. Open a file.
3. Click the Hamburger button.
4. Click the "Send Tab to Device" button.
5. Observe the behavior.

**[Expected results]:**
- Nothing happens, the button is grayed out.

**[Actual results]:**
- The Login prompt or the list of available devices is displayed.

**[Notes]:**
- This issue is also reproducible with the Send Tabs button from "Tabs View".
- Attached a screen recording of the issue: [link](https://drive.google.com/open?id=1cHJLpVwILCn_JFUXNCsWlbulJDkHUyQi).

### PR DESCRIPTION
**Pull request by keianhzo**
Fixes #3228 Send only http/https tabs

### CODE REVIEW

File: app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java [hunk 1]
```diff
@@ -17,6 +17,7 @@
 import android.util.Pair;
 import android.view.LayoutInflater;
 import android.view.View;
+import android.webkit.URLUtil;
```
Comment (bluemarvin) [inline app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java:20]: I don't think we want this dependency?

Comment (bluemarvin) [reply app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java:20]: I guess it is in a lot of places.
