### PR TITLE
Ensure Sessions are recreated correctly when clearing data

### LINKED ISSUE #2356: Performance issues occur after clearing cache or cookies and data
**[Affected Versions]:**
- Firefox Reality version 7-33260123 (6bef00e1)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The headset is turned on and the browser is open.

**[Steps to reproduce]:**
1. Navigate to a webpage.
2. Go to Settings and open the “Privacy & Security” card.
3. Click the "Clear Data" button for the "Cookies and Site Data" or the "Cached Web Content" option.
4. Dismiss the menu and interact with the window.
5. Observe the behavior.

**[Expected results]:**
- The window functions correctly.

**[Actual results]:**
- The page is frozen and the window doesn’t function correctly.

**[Notes]:**
- Only the windows open when clearing the data are affected by this issue.
- The window controls are not affected by this issue.
- Attached is a screen recording of the [issue](https://drive.google.com/file/d/1dJJ347nqivQmOApAEh9AZulcK7OZ1WyP/view?usp=sharing).
- Attached is the logcat of this [issue](https://drive.google.com/file/d/1n9MAdrTOD_PiTrsZa8S9Pc5A8ELCrOBU/view?usp=sharing).

### PR DESCRIPTION
**Pull request by bluemarvin**
- Fixes #2356
- Fixes issue where switching Multiprocess in the developer panel would freeze the session.
- Fixes default private browsing page not getting displayed when recreating a private browsing session.

### CODE REVIEW

File: app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java [hunk 1]
```diff
@@ -1106,13 +1106,13 @@ public void onCurrentSessionChange(GeckoSession aOldSession, GeckoSession aSessi
         } else {
             setPrivateBrowsingEnabled(false);
         }
+        waitForFirstPaint();
```
Comment (keianhzo) [inline app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java]: We don't seem to be executing the first draw callback in some situations like:
- Open a new tab
- Select the previous tab

**Comment by keianhzo** [comment]
Also pausing/resuming the activity makes all the sessions to not receive a first draw call.

**Comment by MortimerGoro** [comment]
I have updated the PR with a fix for the first draw callback issue
