### PR TITLE
Tabs polish

### LINKED ISSUE #2020: App crashes on window.open (tabs)
## Configuration

Firefox Reality version: 6
Firefox Reality build ID: 94c6c127e8bac27bd1c8a99537c5d13dc433052a

Hardware: 

## Steps to Reproduce

1. Go to https://www.w3schools.com/jsref/met_win_prompt.asp
2. Click on "Try it yourself"

## Current Behavior

App crashes

## Expected Behavior

A new session should be opened.

## Context

This only happens in the feature/tabs branch.

## Error Logs and Stack Traces

<details open>

```
2019-10-18 17:48:20.883 6589-6589/org.mozilla.vrbrowser.dev E/GeckoCrashHandler: >>> REPORTING UNCAUGHT EXCEPTION FROM THREAD 1 ("main")
    java.lang.IllegalArgumentException: Must use an unopened GeckoSession instance
        at org.mozilla.geckoview.GeckoSession$3.lambda$handleMessage$4$GeckoSession$3(GeckoSession.java:653)
        at org.mozilla.geckoview.-$$Lambda$GeckoSession$3$W-gnbhMMaqAcPHnPyqZS4Yh6QAs.accept(lambda)
        at org.mozilla.geckoview.GeckoResult.lambda$accept$0(GeckoResult.java:382)
        at org.mozilla.geckoview.-$$Lambda$GeckoResult$I3k4K0DCRrX6z4p5VGaRoaRBTZM.onValue(lambda)
        at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$2$GeckoResult(GeckoResult.java:431)
        at org.mozilla.geckoview.-$$Lambda$GeckoResult$gwCgOUK_EYQn2g6GolfZvo6A_WE.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6144)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

</details>

### LINKED ISSUE #2025: title of FxR home tab is incorrect
In the tabs panel, the text under the content feed thumbnail says the URL of the content feed (webxr.today)

It should say "Firefox Reality Home"

badtabtitle

### PR DESCRIPTION
**Pull request by MortimerGoro**
Fixes #2025. Fixes #2020 

- Tabs UI polish
- Set correct tab title for contend feed
- Correctly handle onNewSession (e.g window.open())

### CODE REVIEW

**Comment by bluemarvin** [comment]
Fixes  #2021

**Comment by MortimerGoro** [comment]
I pushed a commit with the BitmapCache implementation. Fixes #2024

**Comment by MortimerGoro** [comment]
More updates:
- Use a single instance of TabWidget. Improve dismiss detection. Fixes #2026
- Add open new tab notificaion and context menu `open in new tab` action.

**Comment by MortimerGoro** [comment]
More updates:
- Fixed threading problem in BitmapCache
- Downscale Bitmaps before saving them to disk
- Fixes #2028 
- Fixes #1897

File: app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java [hunk 1]
```diff
@@ -328,20 +331,20 @@ private void restore() {
...
 
-        return createSession(settings);
+        return createSession(settings, aOpen);
     }
 
-    private SessionState createSession(@NonNull SessionSettings aSettings) {
+    private SessionState createSession(@NonNull SessionSettings aSettings, boolean aOpen) {
         SessionState state = new SessionState();
         state.mSettings = aSettings;
         state.mSession = createGeckoSession(aSettings);
```
Comment (bluemarvin) [inline app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java]: Please use enum instead of a boolean so it is more obvious what is happening in the code.

**Comment by MortimerGoro** [comment]
Closed via #2028
