### PR TITLE
Pause/resume other windows when entering/exiting immersive mode

### LINKED ISSUE #1746: The videos played in the other windows are not paused when entering immersive mode from a different window
**[Affected Versions]:**
- Firefox Reality 1.4-32450938 (RC2)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The audio settings are turned on and the volume is up.

**[Steps to reproduce]:**
1. Click "+" button in the menu tray to create a new window.
2. Visit the following website "youtube.com" and play a normal video.
3. Click "+" button in the menu tray to create a new window.
4. Visit the following website "https://threejs.org/examples/#webvr_rollercoaster" and enter immersive mode.
5. Observe the behavior.

**[Expected results]:**
- The video played in the other window is paused and there is no audio interference.

**[Actual results]:**
- The video continues to play in the other window and interferes with the audio from the immersive mode. 

**[Notes]:**
- After exiting immersive mode the video from the other window still continues to play. 
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1Ar5TUqLYi94zdFvJR8hTVo7IXC863wWe/view?usp=sharing).

### PR DESCRIPTION
**Pull request by keianhzo**
Fixes #1746 Pause other windows when entering immersive mode.

### CODE REVIEW

File: app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java [hunk 1]
```diff
@@ -395,6 +395,31 @@ public boolean isInPrivateMode() {
...
+        for (WindowWidget window: mRegularWindows) {
+            if (window != mFocusedWindow) {
+                window.onResume();
+            }
+        }
+        for (WindowWidget window: mPrivateWindows) {
+            if (window != mFocusedWindow) {
+                window.onResume();
+            }
+        }
```
Comment (bluemarvin) [inline app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java]: Aren't we pausing private window when in regular browsing mode. Won't this resume them when coming out of immersive mode?

Comment (keianhzo) [reply app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java]: Good catch, fixed. We should only pause/resume de windows in the current mode.

**Comment by keianhzo** [comment]
@MortimerGoro I've updated this to better handle the exit immersive through a whole activity pause case.
